version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pizzashop
    volumes:
      - postgres_data:/bitnami/postgresql

  api: 
    build: .
    container_name: pizza-shop-api
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    environment:
      - DB_URL=postgresql://docker:docker@postgres:5432/pizzashop
      - DATABASE_URL=postgresql://docker:docker@postgres:5432/pizzashop
      
      - API_BASE_URL=http://localhost:3333
      - AUTH_REDIRECT_URL=http://localhost:5173
      
      # Chaves
      - JWT_SECRET_KEY="my-super-secret-key"
      - RESEND_API_KEY="re_123456789" 
      # Nota: Valor fictício no RESEND_API_KEY para passar na validação do Zod.
      
volumes:
  postgres_data: